[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Form handling
[[plugins]]
  package = "@netlify/plugin-forms"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Form settings
[forms]
  # Enable form detection
  enabled = true
  
  # Spam protection
  [forms.spam_protection]
    enabled = true
    
  # Email notifications for form submissions
  # All form submissions will be automatically forwarded to hello@neuralflow.cloud
  # Configure in Netlify dashboard: Site settings > Forms > Form notifications
  # Add email notification to: hello@neuralflow.cloud
  [forms.notifications]
    enabled = true
    email = "hello@neuralflow.cloud"